/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dynamicso_SoUtils */

#ifndef _Included_com_dynamicso_SoUtils
#define _Included_com_dynamicso_SoUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dynamicso_SoUtils
 * Method:    getDynamicsoString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dynamicso_SoUtils_getDynamicsoString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
